src/beans/User.java
package beans;


import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    private static final long serialVersionUID = 1L;

    private int id;
    private String loginid;
    private String password;
    private String confpassword;
    private String name;
    private String branch;
    private String position;
    private Date created_date;
    private Date updatedDate;


    public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
    public String getLoginId() {
		return loginid;
	}
	public void setLoginId(String loginid) {
		this.loginid = loginid;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getConfPassword() {
		return confpassword;
	}
	public void setConfPassword(String confpassword) {
		this.confpassword = confpassword;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getBranch() {
		return branch;
	}
	public void setBranch(String branch) {
		this.branch = branch;
	}
	public String getPosition() {
		return position;
	}
	public void setPosition(String position) {
		this.position = position;
	}
	public Date getCreated_date() {
		return created_date;
	}
	public void setCreated_date(Date created_date) {
		this.created_date = created_date;
	}
	public Date getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
}

src/controller/EditUserServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.User;
import exception.NoRowsUpdatedRuntimeException;
import service.UserService;

/**
 * Servlet implementation class EditUserServlet
 */
@WebServlet("/editUser")
public class EditUserServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

        HttpSession session = request.getSession();
        User loginUser = (User) session.getAttribute("loginUser");

		User ediUser = new UserService().getUser(loginUser.getId());
		request.setAttribute("ediUser", ediUser);

		request.getRequestDispatcher("editUser.jsp").forward(request, response);
	}


	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		HttpSession session = request.getSession();

		List<String> errors = new ArrayList<String>();

		User editUser = getEditUser(request);

		if (isValid(request, errors) == true) {

			try {
                new UserService().update(editUser);

            } catch (NoRowsUpdatedRuntimeException e) {
            	errors.add("他の人によって更新されています。最新のデータを表示しました。データを確認してください。");
                session.setAttribute("errorMessages", errors);


                session.setAttribute("errorMessages", errors);
                request.setAttribute("editUser", editUser);
                request.getRequestDispatcher("editUser").forward(request, response);
                return;
            }

	            session.setAttribute("loginUser", errors);
				response.sendRedirect("./");

	    	} else {
				session.setAttribute("errorMessages", errors);
				request.setAttribute("editUser", editUser);
				request.getRequestDispatcher("editUser.jsp").forward(request, response);
		}
	}


	private User getEditUser(HttpServletRequest request)
			throws IOException, ServletException {

        User editUser = new User();

//        User user = (User) request.getSession().getAttribute("loginUser");

//        editUser.setId(user.getId());
    	editUser.setLoginId(request.getParameter("loginid"));
		editUser.setPassword(request.getParameter("password"));
		editUser.setName(request.getParameter("name"));
		editUser.setBranch(request.getParameter("branch"));
		editUser.setPosition(request.getParameter("position"));
        return editUser;
    }


	private boolean isValid(HttpServletRequest request, List<String> errors) {
		String loginid = request.getParameter("loginid");
		String password = request.getParameter("password");
		String confpassword = request.getParameter("confpassword");
		String name = request.getParameter("name");
		String branch = request.getParameter("branch");
		String position = request.getParameter("position");


			if (StringUtils.isEmpty(loginid) == true) {
				errors.add("ログインIDを入力してください");
			}
			if (loginid.matches("^[0-9a-zA-Z]{6,20}$")) {
			}else{
				errors.add("ログインIDは半角英数字6文字以上20文字以下");
			}
	        if (StringUtils.isEmpty(password) == true) {
	        	errors.add("パスワードを入力してください");
		    }
	        if (password.matches("^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]{6,20}$")) {
			}else{
				errors.add("パスワードは記号を含む半角英数字6文字以上20文字以下");
			}
		    if (StringUtils.isEmpty(confpassword) == true) {
		    	errors.add("確認用パスワードを入力してください");
		    }
			if(!password.equals(confpassword)){
				errors.add("パスワードが一致しません");
			}
	        if (StringUtils.isEmpty(name) == true) {
	        	errors.add("名前を入力してください");
	        }
	        if (StringUtils.isEmpty(branch) == true) {
	        	errors.add("支店名を入力してください");
	        }
	        if (StringUtils.isEmpty(position) == true) {
	        	errors.add("部署・役職を入力してください");
	        }
	        if (errors.size() == 0) {
	            return true;
	        } else {
	            return false;
	        }
	}
}

src/controller/HomeServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import beans.ReText;
import beans.User;
import beans.UserMessage;
import service.MessageService;
import service.ReTextService;

/**
 * Servlet implementation class Home
 */
@WebServlet(urlPatterns = { "/index.jsp" })
public class HomeServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	   @Override
		    protected void doGet(HttpServletRequest request,
		    		HttpServletResponse response) throws IOException, ServletException {

		         List<String> errors = new ArrayList<String>();

		 		 HttpSession session = request.getSession() ;

		    	 User user = (User) request.getSession().getAttribute("loginUser");
		         boolean isShowMessageForm;
		         if (user != null) {
		             isShowMessageForm = true;
		         } else {
		             isShowMessageForm = false;
		         }

		         List<UserMessage> messages = new MessageService().getMessage();

		         List<UserMessage> category = new MessageService()
		        		 .getCategoryMessage(request.getParameter("category"));

		         List<ReText> reTexts = new ReTextService().getReText();

		 		 List<UserMessage> created_date = new MessageService()
		 				 .getCreated_date(request.getParameter("created_date"));


		        request.setAttribute("errors", errors);
		 		session.setAttribute("messages", messages);
		 		session.setAttribute("category", category);
		 		session.setAttribute("reTexts", reTexts);
		 		session.setAttribute("created_date", created_date);
		 		session.setAttribute("isShowMessageForm", isShowMessageForm);

		 		response.sendRedirect("home.jsp");
		    }


	   protected void doPost(HttpServletRequest request,
		            HttpServletResponse response) throws IOException, ServletException {

				HttpSession session = request.getSession();

				String year = request.getParameter("year");
				String month = request.getParameter("month");
				String days = request.getParameter("days");

				List<UserMessage> created_date = new MessageService()
						 .getCreated_date(year + "-" + month + "-" + days);

					request.setAttribute("created_date", created_date);
				    session.setAttribute("created_date", created_date);


			    List<UserMessage> category = new MessageService()
						 .getCategoryMessage(request.getParameter("category"));

					request.setAttribute("category", category);
				    session.setAttribute("category", category);


		        response.sendRedirect("home.jsp");
	   }
}

src/controller/LoginServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import beans.User;
import service.LoginService;

/**
 * Servlet implementation class LoginServlet
 */
@WebServlet("/login")
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

 @Override
	    protected void doGet(HttpServletRequest request,
	            HttpServletResponse response) throws IOException, ServletException {

	        request.getRequestDispatcher("login.jsp").forward(request, response);
	    }

	    @Override
	    protected void doPost(HttpServletRequest request,
	            HttpServletResponse response) throws IOException, ServletException {

	    	String loginid = request.getParameter("loginid");
	        String password = request.getParameter("password");

	        LoginService loginService = new LoginService();
	        User user = loginService.login(loginid, password);

	        HttpSession session = request.getSession();
	        if (user != null) {

	            session.setAttribute("loginUser", user);
	            response.sendRedirect("./");

	        } else {

	            List<String> messages = new ArrayList<String>();
	            messages.add("ログインに失敗しました。");
	            session.setAttribute("errorMessages", messages);
	            response.sendRedirect("login");
	        }
	    }

	}

src/controller/SettingsServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.User;
import service.UserService;

@WebServlet(urlPatterns = { "/settings" })
public class SettingsServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws IOException, ServletException {
		List<User> users = new UserService().getUsers();
		request.setAttribute("users", users);
		request.getRequestDispatcher("settings.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		HttpSession session = request.getSession();

		List<String> errors = new ArrayList<String>();

		User user = new User();

		if (isValid(request, errors) == true) {

			user.setLoginId(request.getParameter("loginid"));
			user.setPassword(request.getParameter("password"));
			user.setName(request.getParameter("name"));
			user.setBranch(request.getParameter("branch"));
			user.setPosition(request.getParameter("position"));

			new UserService().register(user);
			response.sendRedirect("./");
		} else {
			session.setAttribute("errorMessages", errors);
			response.sendRedirect("signup");
		}
	}

	private boolean isValid(HttpServletRequest request, List<String> users) {
		String name = request.getParameter("name");

		HttpSession session = request.getSession();
		session.setAttribute("errorMessages", users);

		if (StringUtils.isEmpty(name)) {
			users.add("登録者はいません");
		}
		if (users.size() == 0) {
			return true;

		} else {
			return false;
		}
	}
}

src/controller/SignUpServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.User;
import service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	 @Override
	    protected void doGet(HttpServletRequest request,
	            HttpServletResponse response) throws IOException, ServletException {

	     request.getRequestDispatcher("signup.jsp").forward(request, response);
	    }

	    @Override
	    protected void doPost(HttpServletRequest request,
	            HttpServletResponse response) throws IOException, ServletException {

	        List<String> messages = new ArrayList<String>();
	        HttpSession session = request.getSession(); //セッションよりログインユーザーの情報を取得

	        if (isValid(request, messages) == true) {

	            User user = new User();

	            user.setLoginId(request.getParameter("loginid"));
	            user.setPassword(request.getParameter("password"));
	            user.setName(request.getParameter("name"));
	            user.setBranch(request.getParameter("branch"));
	            user.setPosition(request.getParameter("position"));

	            new UserService().register(user);


       			 response.sendRedirect("settings");

	        } else {
	            session.setAttribute("errorMessages", messages);
	            response.sendRedirect("signup");
	        }
	    }

		private boolean isValid(HttpServletRequest request, List<String> messages) {

			String loginid = request.getParameter("loginid");
			String password = request.getParameter("password");
	        String confpassword = request.getParameter("confpassword");
			String name = request.getParameter("name");
			String branch = request.getParameter("branch");
			String position = request.getParameter("position");

			if (StringUtils.isEmpty(loginid) == true) {
			    messages.add("ログインIDを入力してください");
			}
			if (loginid.matches("^[0-9a-zA-Z]{6,20}$")) {
			}else{
			    messages.add("ログインIDは半角英数字6文字以上20文字以下");
			}
	        if (StringUtils.isEmpty(password) == true) {
		        messages.add("パスワードを入力してください");
		    }
	        if (password.matches("^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]{6,20}$")) {
			}else{
			    messages.add("パスワードは記号を含む半角英数字6文字以上20文字以下");
			}
		    if (StringUtils.isEmpty(confpassword) == true) {
			    messages.add("確認用パスワードを入力してください");
		    }
//		    String pass =  request.getParameter("password");
//           String cpass = request.getParameter("confpassword");
//			if(password != confpassword){
//				messages.add("パスワードが一致しません");
//			}
	        if (StringUtils.isEmpty(name) == true) {
	            messages.add("名前を入力してください");
	        }
	        if (StringUtils.isEmpty(branch) == true) {
	            messages.add("支店名を入力してください");
	        }
	        if (StringUtils.isEmpty(position) == true) {
	            messages.add("部署・役職を入力してください");
	        }
	        if (messages.size() == 0) {
	            return true;
	        } else {
	            return false;
	        }
	    }
	}

src/controller/TopServlet.java
package controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import beans.ReText;
import beans.User;
import beans.UserMessage;
import service.MessageService;
import service.ReTextService;

/**
 * Servlet implementation class TopServret
 */
@WebServlet(urlPatterns = { "/top" })
public class TopServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

    	 User user = (User) request.getSession().getAttribute("loginUser");

         boolean isShowMessageForm;
         if (user != null) {
             isShowMessageForm = true;
         } else {
             isShowMessageForm = false;
         }

         List<UserMessage> messages = new MessageService().getMessage();
         List<ReText> retexts = new ReTextService().getReText();


         request.setAttribute("messages", messages);
         request.setAttribute("retexts", retexts);
         request.setAttribute("isShowMessageForm", isShowMessageForm);

         request.getRequestDispatcher("top.jsp").forward(request, response);
    }



}

WebContent/editUser.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"  %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ユーザー編集</title>
</head>
<body>

       <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session"/>
            </c:if>

            <div class="header">
                <a href="./">ホーム</a>
            </div>


          <form action="editUser" method="post">

                <input type="hidden" name="id" value="${editUser.id}" id="id" />

                <label for="password">新ログインID</label>
                <input name="loginid" value="${editUser.loginid}" id="loginid"/><br />

                <label for="password">新パスワード</label>
                <input name="password" type="password" id="password"/> <br />

                 <label for="password">パスワード(確認用)</label>
                <input name="confpassword" type="password" id="password"/> <br />

                <label for="name">新名称</label>
                <input name="name" value="${editUser.name}" id="name"/><br />

                <label for="branch">支店</label>
                <input name="branch" value="${editUser.branch}" id="branch"/> <br />

                <label for="position">新所属・役職</label>
                <input name="position" value="${editUser.position}" id="position"/> <br />

                <input type="submit" value="変更" /> <br />
                <a href="settings">戻る</a>
            </form>
            <div class="copyright"> Copyright(c)Your Name</div>
        </div>


</body>
</html>

WebContent/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    <%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
       <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>ホーム画面</title>
       </head>
    <body>
        <div class="main-contents">

           <c:if test="${ not empty errorMessages }">
              <div class="errorMessages">
                   <ul>
                       <c:forEach items="${errorMessages}" var="message">
                           <li><c:out value="${message}" />
                       </c:forEach>
                   </ul>
               </div>
               <c:remove var="errorMessages" scope="session"/>
            </c:if>

            <div class="header">
                <a href="./">ホーム</a>
                <a href="top">新規投稿画面</a>
                <a href="settings">ユーザー管理画面</a>
                <a href="logout">ログアウト</a>
            </div>

             <c:if test="${ empty loginUser }">
  		  	    <div class="profile">
     		      <a href="login">ログイン</a>
           		  </div>
   		  	</c:if>


            <c:if test="${ not empty loginUser }">
           		  <div class="profile">
           		  <a><B><br>＜ログイン中のユーザー＞</B></a>
            	     <div class="name">名前：<c:out value="${loginUser.name}" /></div>
            	     <div class="branch">支店名:<c:out value="${loginUser.branch}" /></div><br />
           		  </div>
   		  	</c:if>


            <form action="./" method="post">
                  <label> カテゴリー:
                  <input type="text" name="category" size="20" maxlength="50"></label>
                  <input type="submit" value="検索">
            </form>


            <form action="./" method="post">
                <br>投稿日:
                <select name="year">
               		<option value=""></option>
            		<option value="2017">2017</option>
            	    <option value="2018">2018</option>
            	    <option value="2019">2019</option>
              	</select>年

                <select name="month">
                   <option value=""></option>
                   <option value="1">1</option>
                   <option value="2">2</option>
                   <option value="3">3</option>
                   <option value="4">4</option>
                   <option value="5">5</option>
                   <option value="6">6</option>
                   <option value="7">7</option>
                   <option value="8">8</option>
                   <option value="9">9</option>
                   <option value="10">10</option>
                   <option value="11">11</option>
                   <option value="12">12</option>
                </select>月


                <select name="days">
                   <option value=""></option>
                   <option value="1">1</option>
                   <option value="2">2</option>
                   <option value="3">3</option>
                   <option value="4">4</option>
                   <option value="5">5</option>
                   <option value="6">6</option>
                   <option value="7">7</option>
                   <option value="8">8</option>
                   <option value="9">9</option>
                   <option value="10">10</option>
                   <option value="11">11</option>
                   <option value="12">12</option>
                   <option value="13">13</option>
                   <option value="14">14</option>
                   <option value="15">15</option>
                   <option value="16">16</option>
                   <option value="17">17</option>
                   <option value="18">18</option>
                   <option value="19">19</option>
                   <option value="20">20</option>
                   <option value="21">21</option>
                   <option value="22">22</option>
                   <option value="23">23</option>
                   <option value="24">24</option>
                   <option value="25">25</option>
                   <option value="26">26</option>
                   <option value="27">27</option>
                   <option value="28">28</option>
                   <option value="29">29</option>
                   <option value="30">30</option>
                   <option value="31">31</option>
                </select>日
                   <input type="submit" value="検索"><hr>
           	</form>


		<c:if test ="${ empty created_date && empty category }">
                 <c:forEach items="${messages}" var="message">
                    <div class="messages">
                      <hr><div class="id"><U>投稿no.<c:out value="${message.id}" /></U></div>
                      <div class="name">名前:<c:out value="${message.name}" /></div>
                      <div class="subject">件名:<c:out value="${message.subject}" /></div>
                      <div class="category">カテゴリー:<c:out value="${message.category}" /></div>
                      <div class="text">本文:<c:out value="${message.text}" /></div>
                      <div class="created_date"><fmt:formatDate value="${message.created_date}" pattern="y年M月d日 HH:mm:ss" /></div><br />
                    </div>

                  <c:forEach items="${reTexts}" var="reText">
                  <c:if test="${ reText.messageid == message.id }">
                  <div class="reText">
                         <div class="reply">＞返信履歴:<c:out value="${reText.reply}" /></div>
                         <div class="name">＞返信者:<c:out value="${reText.name}" /></div>
                         <div class="created_date"><fmt:formatDate value="${reText.created_date}" pattern="y年M月d日 HH:mm:ss" /></div>

					<form action="delete" method="post">
                         <input type="hidden" name="delete" value="${reText.messageid }">
                         <input type="submit" value="削除" >
                    </form>
                  </div>
                  </c:if>
                 </c:forEach>

               		<form action="reText" method="post">
	                     <input type="hidden" name="messageid" value="${message.id}">
	                     newコメント:
	                     <textarea name="reply" cols="35" rows="2" class="reText_box"></textarea>
	                     <br><input type="submit" value="送信"><hr />
           		  	</form>
                 </c:forEach>
           </c:if>
            <c:remove var="delete" scope="session"/>


    	<c:if test ="${not empty created_date}">
                 <c:forEach items="${created_date}" var="created_date">
                      <hr><div class="id"><U>投稿no.<c:out value="${created_date.id}" /></U></div>
                      <div class="name">名前:<c:out value="${created_date.name}" /></div>
                      <div class="subject">件名:<c:out value="${created_date.subject}" /></div>
                      <div class="category">カテゴリー:<c:out value="${created_date.category}" /></div>
                      <div class="text">本文:<c:out value="${created_date.text}" /></div>
                      <div class="created_date"><fmt:formatDate value="${created_date.created_date}" pattern="y年M月d日 HH:mm:ss" /></div><br />

                  <c:forEach items="${reTexts}" var="reText">
                  	<c:if test="${ reText.messageid == created_date.id }">
                	  <div class="reText">
                         <div class="reply">＞返信履歴:<c:out value="${reText.reply}" /></div>
                         <div class="name">＞返信者:<c:out value="${reText.name}" /></div>

                         <form action="delete" method="post">
                         <input type="hidden" name="delete" value="${reText.messageid }">
                         <input type="submit" value="削除" >
                    </form>
                 	 </div>
              		</c:if>
         		  </c:forEach>

       			<form action="reText" method="post">
                 	  <input type="hidden" name="messageid" value="${created_date.id}">
                   		newコメント:
                   		<textarea name="reply" cols="35" rows="2" class="reText_box"></textarea>
                   		<br><input type="submit" value="送信"><hr />
           		</form>
                </c:forEach>
       	  	</c:if>
       	  	 <c:remove var="delete" scope="session"/>


			<c:if test ="${not empty category}">
                 <c:forEach items="${category}" var="category">
                      <hr><div class="id"><U>投稿no.<c:out value="${category.id}" /></U></div>
                      <div class="name">名前:<c:out value="${category.name}" /></div>
                      <div class="subject">件名:<c:out value="${category.subject}" /></div>
                      <div class="category">カテゴリー:<c:out value="${category.category}" /></div>
                      <div class="text">本文:<c:out value="${category.text}" /></div>
                      <div class="created_date"><fmt:formatDate value="${category.created_date}" pattern="y年M月d日 HH:mm:ss" /></div><br />


                  <c:forEach items="${reTexts}" var="reText">
                  	<c:if test="${ reText.messageid == category.id }">
                	  <div class="reText">
                         <div class="reply">＞返信履歴:<c:out value="${reText.reply}" /></div>
                         <div class="name">＞返信者:<c:out value="${reText.name}" /></div>
                         <div class="created_date"><fmt:formatDate value="${reText.created_date}" pattern="y年M月d日 HH:mm:ss" /></div><br />

                         <form action="delete" method="post">
                         <input type="hidden" name="delete" value="${reText.messageid }">
                         <input type="submit" value="削除" >
                         </form>
                 	 </div>
              		</c:if>
         		  </c:forEach>

       			<form action="reText" method="post">
                 	  <input type="hidden" name="messageid" value="${category.id}">
                   		newコメント:
                   		<textarea name="reply" cols="35" rows="2" class="reText_box"></textarea>
                   		<br><input type="submit" value="送信"><hr />
           		</form>
                </c:forEach>
       	  	</c:if>
       	  	 <c:remove var="delete" scope="session"/>
            <br>
            <div class="copyright"> Copyright(c)YourName</div>
       </div>
     </body>
 </html>

WebContent/settings.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>$ユーザー管理</title>
    </head>
    <body>
        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session"/>
            </c:if>

            <div class="header">
         	    <a href="./">ホーム</a>
                <a href="signup">ユーザー新規登録</a>
                <a href="editUser">ユーザー編集</a>
            </div>


             <div class="settings">
             <c:forEach items="${users}" var="user">
                   <hr><div class="loginid">ログインID:<c:out value="${user.loginId}" /></div>
                   <div class="name">名前:<c:out value="${user.name}" /></div>
                   <div class="branch">支店:<c:out value="${user.branch}" /></div>
                   <div class="position">部署・役職:<c:out value="${user.position}" /></div>
                   <div class="created_date"><fmt:formatDate value="${user.created_date}" pattern="y年M月d日 HH:mm:ss" /></div>
             </c:forEach><hr>
             </div>


             <a href="./">戻る</a>

            <div class="copyright"> Copyright(c)Your Name</div>
        </div>
    </body>
</html>